### ISSUE TITLE
Plugin defaults to KV stores

### ISSUE THREAD

**Issue by setswei** [morningconsult/docker-credential-vault-login#72]
This is not a bug or a feature request, its probably more guidance as i am new to using vault

Currently at the moment i am using this docker vault plugin to centralize all my docker repository credentials and the credential helper tool is working for Version 1 KV stores. if version 2 is being used. I receive the error "error reading secret from Vault: error="No username or password found in Vault at path"

My vault agent configuration file is below.

```
auto_auth {
	method "approle" {
		mount_path = "auth/approle"
		config = {
			role_id_file_path = "/Users/HOME/bin/configs/role-id"
			secret_id_file_path = "/Users/HOME/bin/configs/secret-id"
			remove_secret_id_file_after_reading = false
			secret = "secrets/applications/docker/dockerhub"
		}
	}

	sink "file" {
		config = {
			path = "/Users/HOME/bin/configs/.tmp"
		}
	}
}
```

have i missed something or do i need to specify additional configuration to get the credential helper to use version 2 KV stores ?

**Comment by alexdulin** [comment]
Hi @setswei, thanks for your question.

Using the `kv-v2` backend requires changing the path where you are pulling secrets from. The `vault agent` code this project relies on utilizes [consul-template](https://github.com/hashicorp/consul-template) under the hood. In order to access `kv-v2` secrets you need to change your path to specify the `data` part of the backend, like so:

```diff
- secret = "secrets/applications/docker/dockerhub"
+ secret = "secrets/data/applications/docker/dockerhub"
```


You can see [this issue](https://github.com/hashicorp/consul-template/issues/1146#issuecomment-432865861) for more info on the differences between the kv v1 and v2 backends with consul-template.

**Comment by setswei** [comment]
Hi @alexdulin, Thank you for your prompt response. I have updated my configuration and it is now working as expected. Apologies if this was a basic question i have only started using vault recently and the documentation was not very clear around the differences be v1 and v2 kv stores.

I appreciate the assistance
